version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: ./dev.Dockerfile
    image: lukuvinkkikirjasto-dev
    container_name: lukuvinkkikirjasto-dev
    depends_on:
      - db
    ports:
      - 5000:5000
    volumes:
      - ./:/usr/src/lukuvinkkikirjasto
    
  db:
    image: postgres:latest
    container_name: lukuvinkkikirjasto-db
    volumes:
      - postgres-data:/var/lib/postgresql/data/
      - ./database_structure.sql:/docker-entrypoint-initdb.d/database_structure.sql
    env_file:
      - ./.env
    
volumes:
  postgres-data: