version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: ./dev.Dockerfile
    image: lukuvinkkikirjasto-dev
    container_name: lukuvinkkikirjasto-dev
    depends_on:
      - db
    ports:
      - 5000:5000
    env_file:
      - ./.env
    volumes:
      - ./:/usr/src/lukuvinkkikirjasto
    
  db:
    build:
      context: ./
      dockerfile: ./db.Dockerfile
    container_name: lukuvinkkikirjasto-db
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    
volumes:
  postgres-data: